### ISSUE TITLE
Improve admin payment token editor

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#123]
The existing payment token editor for admins is designed for gateways that's have no control panel to manage tokens (a la NETbilling) which makes its use rather limited for modern gateways. Let's improve this:

* view/add/edit/remove tokens from the edit user screen
* force refresh of token data from remote API
* allow the implement gateway to provide validation for new/edited tokens, e.g. must provide last four, card type, etc.

As an example, Authorize.net CIM doesn't return the card type from the remote "get tokens" API call, so if the admin adds a token within the CIM control panel, the extension will retrieve the token (along with the last 4 and expiration date) but without any way of knowing the card type. It then displays as "Credit/Debit Card ending in 1234" with a generic icon instead of a fancy card type icon which makes us :sob: -- with this improvement, the admin could enter the card type and voilà, fancy card type icons!

**Comment by ChaseWiseman** [comment]
@maxrice One question that came up was how to handle Add functionality for gateways that support "get API tokens" vs. those that don't. My initial thought was:

* If the gateway supports get_tokens, then hide Add New and only display a "Refresh" button or similar to pull the latest payment profiles.
* Otherwise, hide the Refresh and just allow manual Add New since that's the only way to do it.

What do you think? Is there a scenario I'm missing where a gateway like CIM would still need to manually Add New? Of course the edit/remove would be the same for both.

Either way, I'm pushing up the base for this feature and will start pulling down and testing against other gateways as I've only really tested with CIM so far. It's not much to look at right now since it's unstyled and not properly scripted, but I hope to finish the UI out today and tomorrow :smile:
