### ISSUE TITLE
Hook into plugins_loaded earlier?

### ISSUE THREAD

**Issue by ragulka** [skyverge/wc-plugin-framework#175]
It seems that we hook into plugins_loaded to initialize the frameworked plugins at default priority (10). This, however, is too late for the plugins to hook into some actions or filters, such as `customize_loaded_components` which is used to adjust the components loaded for WP Customizer. A simple fix for this would be to actually initialize our frameworked plugins at a higher/earlier priority, such as 1 or 5, since most things in WP/WC core use default priority.

As it stands, there's no way to currently hook into that specific hook inside any of the plugin classes, the workaround is to define a global function and hook in there. However, this is suboptimal, since it pollutes the global namespace, and also none of the plugin class instances are available to use.

I'm not sure what the implications for such a change would be, but it would make sense also in the context that `plugins_loaded@10` would then also indicate that frameworked plugins are loaded.

**Comment by maxrice** [comment]
I can't recall if the default priority on `plugins_loaded` was selected for a reason or not. @justinstern may remember. Regardless, this change should be approached with caution. The next backwards-incompatible release that coincides with a WooCommerce compatibility release would be the ideal time to change this so that we ensure every plugin making using of `sv_wc_plugins_loaded` gets adequate testing.

**Comment by justinstern** [comment]
there should be no issue per se with bumping the priority [on that action](https://github.com/skyverge/wc-plugin-framework/blob/85a9c4d4048acc4e6670803589be6bfb1d5e6416/woocommerce/class-sv-wc-framework-bootstrap.php#L69) as the intention was to bootstrap all the framework plugins once _all_ plugins have been loaded, which should be the case as early as `plugins_loaded@0` right?

The issue that we need to all be aware of, and the underlying flaw with the framework as I originally architected it, is due to the fact that the _first_ loaded framework plugin (which happens alphabetically) will have its `SV_WC_Framework_Bootstrap` class loaded, regardless of there being a higher versioned (backwards compatible or not) framework plugin active. In other words, while the bootstrap class guarantees to you that the highest versioned _framework classes_ will be loaded, there's no guarantee that the highest versioned _bootstrap class_ will be used.

So although we should be able to safely increase that priority, we can't _rely_ on that priority being used in the wild at all times.

As a concrete example, lets say we have a shop with an active WooCommerce Address Validation using an older (incompatible) version of the framework, alongside a shiny new WooCommerce PDF Product Vouchers using the latest and greatest, with the updated `plugins_loaded` priority. The bootstrap code from the old WooCommerce Address Validation will be found first during plugin loading, and be used. We'll get that nice "incompatible" message telling the merchant to update or deactivate WooCommerce Address Validation, however if they don't take action, the bootstrap will forever be stuck hooking into `plugins_loaded@10`

The implications that are coming to mind right now are:

1. If it's important to load the classes earlier, and it seems that it might be, we should go ahead and do so for the next backwards-incompatible release as @maxrice said. it's better to make these changes sooner than later
1. We'll have to gracefully handle the case of plugin being loaded later than is optimal. This might even mean just not fatal error'ing, and perhaps roadblocking use of the plugin until the backwards incompatible framework message is resolved by the shop admin.
1. I'm not certain that the global function solution mentioned above is a possibility, given that no classes will be loaded, as @ragulka pointed out
1. FWIW all frameworked plugins are expected to hook into our `sv_wc_framework_plugins_loaded` action in place of `plugins_loaded`, so any plugins using that action will get fired at the new higher priority.

**Comment by ChaseWiseman** [comment]
Closing this out because plugins using v5 now use a loader class and can specify their own `plugins_loaded` priority if needed: https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/woocommerce-framework-plugin-loader-sample.php#L90
