### ISSUE TITLE
WC - Payment Error;

### ISSUE THREAD

**Issue by silasmckenna** [skyverge/wc-plugin-framework#241]
```
Uncaught TypeError: $(...).payment is not a function
    at SV_WC_Payment_Form_Handler.window.SV_WC_Payment_Form_Handler.SV_WC_Payment_Form_Handler.format_credit_card_inputs (sv-wc-payment-gateway-payment-form.min.js?ver=4.6.0:123)

Fields aren't validating and it's breaking the woocommerce chain

```

I get the above error when trying to load a woocommerce checkout page by default (no customization and on a blank install even).

```
      SV_WC_Payment_Form_Handler.prototype.format_credit_card_inputs = function() {
        $('.js-sv-wc-payment-gateway-credit-card-form-account-number').**payment('formatCardNumber')**.change();
        $('.js-sv-wc-payment-gateway-credit-card-form-expiry').**payment('formatCardExpiry')**.change();
        $('.js-sv-wc-payment-gateway-credit-card-form-csc').**payment('formatCardCVC')**.change();
        return $('.js-sv-wc-payment-gateway-credit-card-form-input').on('change paste keyup', (function(_this) {
          return function() {
            return _this.do_inline_credit_card_validation();
          };
        })(this));
      };
```

What file does this function `payment` come from?  Do I need to include it manually or is something messed up?

**Comment by silasmckenna** [comment]
I found this plugin: https://github.com/stripe/jquery.payment which seems to have fixed the error I'm receiving; however, this project says it is deprecated.

**Comment by bekarice** [comment]
@silasmckenna thanks for reaching out here! This repo is intended for development of our plugin framework rather than support for payment gateways. I can't replicate any issues with CIM, so It looks like you're running into a conflict of some kind. You can [get in touch with the support team here instead](https://woocommerce.com/my-account/marketplace-ticket-form/) to assist in narrowing this down. Cheers!
