### ISSUE TITLE
Implement/test subscriptions support with held order

### ISSUE THREAD

**Issue by justinstern** [skyverge/wc-plugin-framework#3]
Test and implement a solution for a subscriptions order that is held.  No clue what this looks like

**Comment by maxrice** [comment]
@thenbrent - can you comment on this? specifically:

>It looks like we're not handling holds during renewals yet, though I think the proper course of action is to simply mark the order as on-hold and allow subs to handle the rest.

Should payment gateway implementations be doing anything special when a payment is "held"? Does Subscriptions consider that a failure?

**Comment by thenbrent** [comment]
> Should payment gateway implementations be doing anything special when a payment is "held"? Does Subscriptions consider that a failure?

What's a "held" payment? Is that like an authorisation without capture?

If so, Subscriptions doesn't provide any special API for that but you should be able to just handle it however you would with a normal order (in Subs v2.0 at least, where the renewal order is generated _before_ the gateway hook is triggered and that's the main, hopefully only, object you need to interact with, e.g. `$renewal_order->payment_complete()`).

I'm assuming that would usually be something like "on checkout, authorise amount, when the order is changed to "Completed" capture the amount". So for renewal you'd do something like "on renewal, authorise amount, when the renewal order is changed to "Completed" capture the amount".

If it's something else, the basic flow is:

1. Subscriptions puts the subscription on-hold
2. Subscriptions creates a renewal order (at the moment, this has the status of "on-hold" for backward compatibility, but we may change it to "pending")
3. Subscriptions triggers the gateway hook to process payment and passes it renewal order

You can do whatever you want with that order after that. But if `payment_complete()` is marked on the order, then Subscriptions will reactivate the subscription (otherwise, it will remain on hold).

**Comment by maxrice** [comment]
@thenbrent 

>What's a "held" payment? Is that like an authorisation without capture?

Yeah, generally either a authorized but not captured payment, or a payment that was not settled due to fraud, etc.

It looks like we're doing this correctly already then, as `WC_Order::payment_complete()` is not called when an order has been marked as `on-hold`. For gateways that support capturing charges from the admin, `payment_complete()` is called so that should take care of reactivating the subscription.

thanks! :smile_cat:
