### ISSUE TITLE
Refactor Direct Payment Gateway Class

### ISSUE THREAD

**Issue by maxrice** [skyverge/wc-plugin-framework#86]
The [`SV_WC_Payment_Gateway_Direct`](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/class-sv-wc-payment-gateway-direct.php) class is our 2nd longest framework class, over 2200 lines. There's some non-gateway specific functionality that could refactored into separate classes to make things a bit easier to maintain:

1) Subscription/Pre-Order Handling - probably best done as part of #80 
2) Tokenization - all methods, but particularly [`get_payment_methods()`](https://github.com/skyverge/wc-plugin-framework/blob/master/woocommerce/payment-gateway/class-sv-wc-payment-gateway-direct.php#L1744-L1826) needs to be refactored into smaller methods.

Class instances for both could be attached to the direct gateway class instance and then utilized like: `$gateway->payment_tokens()->get()`, `$gateway->payment_tokens()->update()`, etc. The only question here is how difficult it makes it for implementing gateways to override subscription/pre-orders/tokenization methods as needed. Provided we implement the class instance getters properly (e.g. `payment_tokens()` is easily overridable) then implementations should be able to return their own class instance.

We can maintain backwards compatibility (if desired) by leaving the existing methods in, though I'm not sure we need to given there's only 5 SV-implement gateways at the moment.

**Comment by maxrice** [comment]
@justinstern curious for your thoughts here, particularly on making it somewhat reasonable for gateways to override methods as needed. It seems a bit lame to force a gateway to create an entirely separate file just to override a single method, but I don't see any other way around it.

**Comment by justinstern** [comment]
ha ha, now you're getting an idea of why I just went with the one giant class file ;)

There's certainly alternatives to having to subclass the delegated class in order to override a single method, but I don't know if you'll like them. Here's one simple implementation, using magic methods:

``` php
class Gateway {
  protected $payment_tokens;
  
  public function __construct() {
    $this->payment_tokens = $this->build_payment_tokens();
  }
  
  public function build_payment_tokens() {
    return new PaymentTokens();
  }
  
  public function get_payment_tokens() {
    return $this->payment_tokens;
  }
  
  public function __call( $name, $arguments ) {
  	if ( strpos( $name, 'payment_tokens' ) === 0 ) {
  	  // delegate any missing method that begins with "payment_tokens" to the PaymentTokens member
  	  $function_name = substr( $name, 15 );
  	  return call_user_func_array( array( $this->payment_tokens, $function_name ), $arguments );
  	} else {
  	  // ...
  	}
  }
}

class SomeRealGateway extends Gateway {
  
  // "override" a method from the PaymentTokens class
  public function payment_tokens_get_foo() {
    // call to "parent"
    return $this->payment_tokens->get_foo() . 'bar';
  }
  
  // "override" a method with arguments from the PaymentTokens class
  public function payment_tokens_blah( $x ) {
    // call to "parent"
    $y = $this->payment_tokens->blah( $x );
    return $y * 2;
  }
}

class PaymentTokens {
  public function hello( $who ) {
    echo "hello {$who}!";
  }
  public function hello_world() {
    $this->hello( 'world' );
  }
  public function get_foo() {
  	return "foo";
  }
  public function blah( $x ) {
  	return $x * 2;
  }
}

$gateway = new SomeRealGateway();

// delegate to inner class without an argument
$gateway->payment_tokens_hello_world();

# => hello world!

// delegate to inner class with an argument
$gateway->payment_tokens_hello( 'max' );

# => hello max!

// overridden methods
echo $gateway->payment_tokens_get_foo();

# => foobar

echo $gateway->payment_tokens_blah( 2 );

# => 8
```

What's fun about this is it allows you to either call the `PaymentTokens` methods through the inner class: `$gateway->get_payment_tokens()->hello_world()` or directly on the gateway class: `$gateway->payment_tokens_hello_world()` and lets you either "override" a method on the parent class, or replace the entire inner `PaymentGateways` class if so desired

**Comment by maxrice** [comment]
@justinstern playing around a bit with this and it works well. The only roadblock I see is that when moving methods out of the direct gateway into individual classes, any methods that make use of protected methods from the gateway class no longer function. While we can certainly change method visibility around, it feels like quite a lot would need to change. Maybe this is a natural consequence of this type of refactoring, but I'm curious if you have other ideas.

**Comment by justinstern** [comment]
@maxrice so for example payment token method that you're extracting into the new helper class, and which itself calls a protected method on the main gateway class which can't also be extracted to just the payment token class?

Since the methods will now be called from another class they'll have to be made public, no real way around it at the moment.

Some other alternatives: multiple inheritance, which PHP sadly does not support. They do have a workaround called [traits](http://php.net/manual/en/language.oop5.traits.php) that would probably be useful here, but requires PHP 5.4

**Comment by maxrice** [comment]
moving this to 4.3 milestone, we've made some progress here with moving the subscriptions/pre-orders integration handling in their own classes.
